### ISSUE TITLE
 Issue: Unable to Configure DocuGen with OLLama in VS Code

### ISSUE THREAD

**Issue by HCRitter** [iamkaranvalecha/DocuGen#57]
### Issue: Unable to Configure DocuGen with OLLama in VS Code

Hi there, 

I'm trying to set up DocuGen with OLLama in Visual Studio Code, but I’m having trouble finding the right configuration settings in the documentation.

Here's what I've encountered so far:
1. **API Key Configuration**: I initially struggled to identify the correct API key, but I resolved this by using `'ollama'` as the key string.
2. **Model Endpoint Error**: VS Code's DocuGen extension is flagging an issue with the `docugen.modelEndpoint` setting. I've tried several endpoints, including:
   - `http://localhost/`
   - `http://localhost:11434/`
   - `http://localhost:11434/v1/chat/completions`

However, none of these configurations have worked so far.

### Request for Assistance
Has anyone successfully configured DocuGen with OLLama in VS Code? If so, could you share the correct settings or any tips to help resolve this issue? 

Thanks in advance for any guidance! 😊

**Comment by iamkaranvalecha** [comment]
@HCRitter 

Thank you for reaching out and for the detailed feedback! We're happy to let you know that a fix for configuring DocuGen with Ollama in Visual Studio Code has been released. We've also made a note of it & fix will be released for GitHub Action too

You should now be able to configure DocuGen seamlessly with Ollama

**Sample Configuration for Ollama:**

![image](https://github.com/user-attachments/assets/d4d08dd5-7e17-45e6-87fb-2b8bb1386fd1)


Thank you for reaching out and for the detailed feedback!

Please update to the latest version of DocuGen, and these configurations should work smoothly. If you encounter further issues, don't hesitate to reach out. Thank you again for your patience, and happy documenting! 😊
